;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua--prefix-override-handler
        cua-cut-region
        cua-delete-region
        cua-paste
        dabbrev-expand
        indent-for-tab-command
        python-backspace
        python-electric-colon
        sgml-close-tag
        smex
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        ido-switch-buffer
        ))
