;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        coffee-dedent-line-backspace
        comment-dwim
        cua--prefix-override-handler
        cua-cut-region
        cua-delete-region
        cua-paste
        cua-paste-pop
        cursor-down-slightly
        cursor-up-slightly
        dabbrev-expand
        handle-select-window
        helm-confirm-and-exit-minibuffer
        ignore
        indent-for-tab-command
        org-end-of-line
        org-force-self-insert
        org-metaright
        org-self-insert-command
        python-backspace
        python-electric-colon
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        recenter
        sgml-close-tag
        smex
        upcase-region
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ido-switch-buffer
        ))
